version: '3.7'

services:
  prod-web:
    build:
      context: ./fusus
      dockerfile: Dockerfile.prod
    command: gunicorn fusus.wsgi:application --bind 0.0.0.0:8081 --workers 2 --threads 2 --worker-class gevent
    expose:
      - 8081
    env_file:
      - ./.env.prod
    networks:
      - prod

  prod-nginx:
    build: ./nginx_prod
    ports:
      - 8081:80
    depends_on:
      - prod-web
    networks:
      - prod

  prod-db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fusus_db_user
      - POSTGRES_PASSWORD=fusion
      - POSTGRES_DB=fusus_db
    networks:
      - prod

networks:
  prod:

volumes:
  postgres_data:
